---
title: "UW 520"
subtitle: "Lecture 6 - Notes"
author: "Lin Gui"
output:
  html_document:
    toc: true
    number_sections: true
---
<span id="jump"></span>

$\newcommand{st}{\h s_\tau}$
$\newcommand{kp}{^{(p)}}$
$\newcommand{kd}{^{(d)}}$

[Back](course_uw_520.html)

# Nonparametric Spectral Estimation

Nyquist Frequency $f_N=\frac 1 {2\Delta t}$

goal

use realization of $X_0,\cdots,X_{N-1}$ observations to estimate $S(\cdot)$

based on
$$
S(f)=\Delta_t\suminf \tau s_\tau\etpin{f\tau\Delta_t}
$$

[up](#jump)

# The Sample Mean

## estimate $\mu$
$$
\overline X=\frac 1 N\sumsubtri t 0 {N-1}X_t\\
$$
unbiased
$$
E\bra{\overline X}=\mu
$$
consistent
$$
\t {for every }\epsi,\liminf N \t P[\abs{\overline X - \mu}>\epsi]=0\\
\t P[\abs{\overline X-\mu}>\epsi]\leq\frac{\var\bra{\overline X}}{\epsi^2}
$$
assume $\sum_\tau\abs{s_t}<\infty$,
$$
\var\bra{\overline X}=\frac 1 N \sumsym\tau{(N-1)}(1-\frac{\abs\tau}N)s_\tau\\
\liminf N N\var\bra{\overline X}=\frac{S(0)}{\Delta _t}
$$
if $S(0)\neq 0$,
$$
\var\bra{\overline X}\approx\frac{S(0)}{N\Delta_t}
$$

## estimate $\mu$ , another
$$
\h\mu\triangleq \frac{\t O_N^T\Sigma\expn 1 \t X}{\t O_N^T\Sigma\expn 1\t O_N}
$$
	where $\t O_N$ is vector of $N$ ones, and $\Sigma$ is covariance matrix for $X_0,\cdots,X_{N-1}$

	called best linear unbiased estimator

asymptotically efficient
$$
\liminf N \frac{\var\bra{\h \mu}}{\var\bra{\overline X}}=1
$$
**if $S(f)\rightarrow 0$ rapidly as $f\rightarrow 0$, then $\overline X$ can be quite inefficient.**

> $S(f)\rightarrow 0$, so $s_\tau$ is very wide

[up](#jump)

# Estimation of ACVS

## estimate ACVS $s_\tau$
$$
\h s_\tau^{(u)}=\frac 1 {N-|\tau|}\sumsubtri t 0 {N-|\tau|-1}(X_{t+|\tau|}-\overline X)(X_t-\overline X)\\
$$
replace $\overline X$ by $\mu$, then **unbiased**
$$
\frac 1 {N-\abs\tau}\sumsubtri t 0{N-\abs\tau-1}E\bra{(X_{t+\abs\tau}-\mu)(X_t-\mu)}=s_\tau
$$

## estimate ACVS, another
$$
\h s_\tau^{(p)}=\frac 1 N \sumsubtri t 0 {N-\abs\tau-1}(X_{t+\abs\tau}-\overline X)(X_t-\overline X)=(1-\frac{\abs\tau}N)\h s_\tau^{(u)}
$$
**replace $\overline X$ by $\mu$, then biased**
$$
\frac 1 N\sumsubtri t - {N-\abs\tau-1}E\bra{(X_{t+\abs\tau}-\mu)(X_t-\mu)}=\lrbra(){1-\frac{\abs\tau}N}s_\tau
$$

> if $\overline X$ is used rather than $\mu$, then $\h s_\tau^{(p)}$ can actually be less biased than $\h s_\tau^{(u)}$

[up](#jump)

# Why prefer $\h s_\tau^{(p)}$?

## MSE
$$
\t{MSE}\bra{\h s_\tau^{(p)}}=(1-\frac{\tau}N)^2\var\bra{\h s_\tau^{(u)}}+(E\bra{\h s_\tau^{(p)}}-s_\tau)^2\\
\t{MSE}\bra{\h s_\tau ^{(u)}}=\var\bra{\h s_\tau^{(u)}}+(E\bra{\h s_\tau^{(u)}}-s_\tau)^2
$$

* Riemann-Lebesgue lemma

  $s_\tau\rightarrow 0$ as $\tau\rightarrow\infty$, and $\h s_\tau^{(p)}$ mimics this as $\tau\rightarrow N$, because
  $$
  \h s_\tau^{(p)}=\lrbra(){1-\frac{\abs\tau}N}\h s_\tau^{(u)}
  $$

* $\bra{\st^{p}}$ is always positive semidefinite

[up](#jump)

# The Periodogram

$$
\h S^{(p)}(f)=\Delta_t \sumsym \tau{(N-1)} \st ^{(p)} \etpin{f\tau\Delta_t}\\
\h S^{(p)}(f)=\frac{\Delta_t}N\abs{\sumsubtri t 0 {N-1}X_t\etpin{ft\Delta_t}}^2\\
$$

> Proof equivalent $\t FT\bra{X*X_t}=\abs{\t{FT}\bra{X_t}}^2$

at Fourier frequencies $f_k=\frac k N \Delta t$
$$
\h S^{(p)}(f_k)=\frac{\Delta_t}N\abs{\sumsubtri t 0 {N-1}X_t\etpin{kt/N}}^2
$$

>  compute via DFT

$$
\st ^{(p)}=\intsym{f_N} \h S^{(p)}(f)\etpi{f\tau\Delta_t}\d f\\
\st^{(p)}=\frac 1{2N\Delta_t}\sumsubtri k {-(N-1)} N\h S^{(p)}(\tilde f_k)\etpi{\tilde f_k\tau\Delta_t}
$$

> Why $f_N$, not $\infty$??????????

relationship(DFT)
$$
S_k=\Delta_t\sumsubtri \tau 0{N-1}\h s_\tau^{(p)}\etpi{k\tau/N}\\
S_k+S^*_k-\h s_0^{(p)}=\h S^{(p)}(f_k)
$$

> given just $\h S^{(p)}(f_k)$'s, can't recover $S_k$ and hence $\h s_\tau^{(p)}$'s

## Sampling Properties of Periodogram

* Ideal

  * $\bra{\h S^{(p)}(f)\approx S(f)}$ for all $f$ (unbiasedness)
  * $\var\bra{\h S^{(p)}}\rightarrow 0$ as $N\rightarrow \infty$ (consistency)
  * $\cov \bra{\h S^{(p)}(f'),\h S^{(p)}(f)}\approx 0$(uncorrelatedness)

* First Moment Properties
  $$
  E\bra{\h S\kp(f)}=\Delta_t\sumsym\tau{(N-1)}\lrbra(){1-\frac {\abs\tau} N}s_\tau \etpin{f\tau \Delta_t}\\
  =N\Delta_t\intsym{f_N}D_N^2([f-f']\Delta_t)S(f')\d f'\\
  \bra{r_t}\leftrightarrow D_N(\cdot)\\
  \bra{1-\frac{\abs\tau}N}\leftrightarrow D_N^2(\cdot)
  $$

 * Fejer's Kernel
   $$
   E\bra{\h S\kp (f)}=\intsym {f_N}\mathcal F(f-f')S(f')\d f'\\
     \mathcal F(f)= N\Delta_tD_N^2(f\Delta_t)\\
     =\frac{\Delta_t \sin^2(N\pi f\Delta_t)}{N\sin^2(\pi f\Delta_to)}\\
     =\frac{\Delta_t}{N}\sumsubtri t 0 {N-1}\sumsubtri u 0 {N-1}\etpin{f(t-u)\Delta_t}
   $$

   * as $N\rightarrow \infty$, $\cal F$ acts like $\delta$ function
   * asymptotically unbiased

$$
\liminf N E\bra{\h S\kp (f)}=S(f)
$$
	 *dynamic range*
$$
d\triangleq 10\log_{10}(\frac{\max_f S(f)}{\min _f S(f)})
$$

[up](#jump)

# Tapering

[up](#jump)

## preclude to tapering

$X_0,\cdots,X_{N-1}, \h X_N$ 

prediction error: $X_0-\h X_N$, **sharp discontinuty**

tapered

$h_0(X_0-\overline X)\cdots, h_{N-1}(X_{N-1}-\overline X)$

## Bias Reduction

$$
\newcommand{kd}{^{(d)}}
J(f)\triangleq \Delta_t^{1/2}\sumsubtri t 0 {N-1} h_t X_t\etpin{ft\Delta_t}\\
\h S\kd(f)=\abs{J(f)}^2\\
E\bra{\h S^{(d)}(f)}=\intsym{f_N}\mathcal H(f-f')S(f')\d f'\\
\bra{h_t}\leftrightarrow H(\cdot)\\
\mathcal H(f)=\frac 1 {\Delta_t}\abs{H(f)}^2
$$

## Slepian data tapers

$$
\max\beta^2(W)=\frac{\intsym W \mathcal H(f)\d f}{\intsym{f_N} \mathcal H(f)\d f}\\
h_t\approx CI_0(\pi W(N-1)(1-([2t+1-N]/N)^{1/2})
$$

## tradeoffs

* reducing bias due to leakage
* introducing bias due th the width of central lobe(smearing or loss of resolution)

not particularly useful for SDFs with samll dynamic range, potentially useful for SDFs with large dynamic range

# ACVS and Normalization

$$
E\bra{\st^{(d)}}=s_\tau\sumsubtri t 0 {N-\abs \tau-1}h_{t+\abs\tau}h_t\\
E\bra{\h S^{(d)}(f)}=\Delta_t\sumsym\tau{(N-1)} s_\tau(\sumsubtri t 0{N-\abs\tau - 1}h_{t+\abs\tau}h_t)\etpin {f\tau\Delta_t}
$$

## Normalization 1

for $\tau=0$,
$$
E\bra{\h s_0^{(d)}}=s_0\sumsubtri t 0 {N-1} h_t^2
$$
require $\sum_t h_t^2=1$

## Normalization 2: restoration of powe

$$
\h s_0^{(d)}=\h s_0^{(p)}\\
\sumsubtri t 0 {N-1} (h_tX_t)^2=\frac 1 N\sumsubtri t 0 {N-1}X_t^2
$$

# Estimation of $\mu$

$$
\tilde \mu=\sumsubtri t 0 {N-1}h_tX_t/\sumsubtri t 0 {N-1}h_t
$$
then
$$
\h S^{(d)}(0)=\Delta_t\abs{\sumsubtri t 0 {N-1}h_t(X_t-\tilde \mu)}^2=0
$$

# Measuring Width of Central Lobe of $\mathcal H(\cdot)$

$$
H(-f_0)=H(f_0)=\frac {H(0)}2\\
\t{width}_{\t{hp}}\bra{\mathcal H(\cdot)}\triangleq 2f_0\\
\t{width}_v\bra{\mathcal H(\cdot)}=12\lrbra () {\intsym{f_N}\phi^2\mathcal H(\phi)\d \phi}^{1/2}\\
=\frac 1 {\Delta_t}\lrbra (){1+\frac {12}{\pi^2\Delta_t}\sumsubtri \tau 1 {N-1}\frac{(-1)^\tau}{\tau^2}h^*h}^{1/2}\\
h*h_\tau=\Delta_t\sumsubtri t 0{N-\abs\tau-1}h_{t+\abs\tau}h_t
$$
measure of bias
$$
b(f)=E\bra{\h S^{(d)}(f)}-S(f)\approx\frac{S''(f)}{24}(\t{width}_v\bra{\mathcal H(\cdot)})^2
$$
autocorrelation width
$$
\t{width}_{\t a}\bra{H(\cdot)}=\frac{(\intsym{f_N}\mathcal H(f)\d f)^2}{\intsym{f_N}\mathcal H^2(f)\d f}\\
=\frac{\Delta_t}{\sumsym\tau{N-1}(h*h_\tau)}^2\triangleq B_{\mathcal H}
$$

> if $\abs{f-f'}\geq B_{\mathcal H}$, then $\hat S^{(d)}(f), \h S^{(d)}(f')$ are approximately uncorrelated
>
> Why????

[Back](#up)

## End Point Mathing

$$
\tilde X_t=X_t-X_0-\frac{X_{N-1}-X_0}{N-1}t, t=0,\cdots,N-1
$$

## Reflection Boundary Conditions

$X_0,\cdots,X_{N-1},X_{N-1},\cdots,X_0$ or

$X_0,\cdots,X_{N-2},X_{N-1},X{N-2},\cdots,0$

# Prewhitening: general of AR model

$$
Y_t\triangleq\sumsubtri l 0{L-1}g_lX_{t+L-1-l},0\leq t\leq M-1, M=N-L+1\\
\h S_Y^{(d)}(f)=\Delta_t\abs{\sumsubtri t 0{M-1}h_tY_t\etpin{ft\Delta_t}}^2\\
\h S_X^{(pc)}(f)=\frac{\h S_Y^{(d)}(f)}{\abs{\sumsubtri l 0{L-1}g_l\etpin{fl\Delta_t}}^2}
$$

# Rejection Filtration

suppose need $S(\cdot)$ only over $[f_{(L)},f_{(H)}]$

design band-pass filter to attenuate $\abs f\notin[f_{(L)},f_{(H)}]$

# Statistical Properties of $\h S^{(d)}(\cdot)$

$\newcommand{dt}{\Delta_t}$

## Re and Im

$$
J(f)=\dt^{1/2}\sumsubtri t 0 {N-1}h_tX_t\etpin{ft\dt}=A(f)-iB(f)\\
A(f)=\dt^{1/2}\sumsubtri t 0 {N-1}h_t X_t\cos(2\pi ft\dt)\\
B(f)=\dt^{1/2}\sumsubtri t 0{N-1}h_tX_t\sin(2\pi ft\dt)\\
\abs{J(f)}^2=\h S^{(d)}(f)=A^2(f)+B^2(f)\\
E\bra{J(f)}=E\bra{A(f)}=E\bra{B(f)}=0\\
\var\bra{A(f)}=\sigma^2\dt\sumsubtri t 0{N-1}h_t^2\cos^2(2\pi ft\dt)\\
\var\bra{B(f)}=\sigma^2\dt\sumsubtri t 0{N-1}h_t^2\sin^2(2\pi ft\dt)\\
\cov\bra{A(f),A(f')},\cov\bra{B(f),B(f')},\cov\bra{A(f),B(f')}
$$

## Special case:$h_t=1/\sqrt{N}$

* $A(f_k),B(f_k)$ are Gaussian and independent

* $\dfrac{A(f_k)}{\sigma^2\dt/2^{1/2}}=\dfrac{A(f_k)}{\sqrt{S(f_k)/2}}$ and $B(\cdot)$ are IID $N(0,1)$

* $\h S\kp (f_k)\mathop=\limits^\d S(f_k)\chi_2^2/2$
  $$
  E\bra{\h S\kp(f_k)}=S(f_k)\\
  \var\bra{\h S\kp(f_k)}=S^2(f_k)
  $$
  if $f_k=0$ or $f_N$
  $$
  \h S\kp(f_k)\mathop =\limits^\d S(f_k)\chi_1^2
  $$

* $\cov\bra{\h S\kp(f_j),\h S\kp(f_k)}=0, f_j\neq f_k$

## general case

$\bra{X_t}$ not necessarily Gaussian,

 $S(\cdot)$ not necessarily white,

 $f$ not necessarily a Fourier frequency

### as $N\rightarrow\infty$

$$
\h S\kp(f)\mathop=^\d S(f)\chi_2^2/2,0<f<f_N\\
\h S\kp(f)\mathop=^\d S(f)\chi_1^2,f=0,f_N\\
\cov\bra{\h S\kp(f_j),\h S\kp(f_k)}=0,f_j\neq f_k
$$
approximately uncorrelated over $f_k$'s'

### odd/even

$N/2+1$ uncorrelated RVs when $N$ is even

$(N+1)/2$ when $N$ is odd

### percentage point

$\newcommand{kd}{^{(d)}}$
$$
\t P\lrbra [] {Q_2(p)\leq\dfrac{2\h S\kd(f)}{S(f)}\leq Q_2(1-p)}=1-2p\\
=\t P\lrbra[]{\frac{2\h S^{(d)}(f)}{Q_2(1-p)}\leq S(f)\leq \frac{2\h S^{(d)}(f)}{Q_2(p)}}
$$
$100(1-2p)%$ CI for $S(f)$
$$
\lrbra[]{-\frac{\h S\kd(f)}{\ln(p)},-\frac{\h S\kd(f)}{\ln(1-p)}}
$$
$10(1-2p)$ CI for $10\log_{10}(S(f))$
$$
10\log_{10}\times\t{above}
$$
length of this CI
$$
10\log_{10}\lrbra(){\frac{Q_2(1-p)}{Q_2(p)}}
$$
p=0.025 to obtain a $95%$ CI
$$
[10\log_{10}(\h S\kd (f))-5.67,10\log_{10}(\h S\kd(f))+15.97 ]
$$
**above results holds for all direct spectral estimators**

### Cov

$$
\cov\bra{\h S\kd(f),\h S\kd (f')}\leq\abs{C\intsym{f_N}\abs{H(f-f'+v)}\cdot\abs{H(v)}\d v}^2\\
\t {where }C\triangleq S_{\max}/\dt,\bra{h_t}\leftrightarrow H(\cdot)
$$
**says**
$$
\cov\bra{\h S\kd (f),\h S\kd(f')}\approx 0,\t {if }\abs{f'-f}>\t{width of central lobe of }\abs{H(\cdot)}
$$
uncorrletated over coarser grid than $f_k$'s:
$$
\h S\kd(0),\h S\kd(\frac c{N\dt}),\cdots,\h S\kd(\frac{Kc}{N\dt})
$$
where $\frac {Kc}{N\dt}\leq f_N<\frac{(K+1)c}{N\dt}$

* typically $c=2,4$
* yields $K+1<N/2+1$ uncorrelated RVs
* using standard measure of effective bandwidth $B_{\mathcal H}$


* var

  holds for all $N$: $\h S\kd(f)$ inconsistent unless $S(f)=0$

* Why does $\h S\kd(\cdot)$ look smoother than $\h S\kp(\cdot)$?

### Probability Density Function for $\h S\kd (f)$

$$
\h S\kd(f)\mathop=^\d S(f)\chi_2^2/2\\
10\log(S(f)\chi_2^2/2)=10\log(S(f)/2)+10\log(\chi_2^2)\\
\triangleq10\log(S(f)/2)+V\\
f_V(v)=\frac{\log (10)}{20}10^{v/10}e^{-(10^{v/10})/2}
$$
**$10\log(\cdot)$ acts as a variance stabilizing transformation**

# A Test for White Noise

$$
\mathcal P_k\triangleq \dfrac{\sumsubtri j 1 k\h S\kp(f_j)}{\sumsubtri j 1 M\h S\kp(f_j)},k=1,\cdots,M-1
$$
where $M\triangleq \lfloor (N-1)/2\rfloor$

* plot $\mathcal P_k$ versus $f_k$ 

* plot lines
  $$
  L_u(f)\triangleq \frac{fN\dt -1}{M-1}+\tilde D(\a)\\
  L_l(f)\triangleq \frac{fN\dt}{M-1}-\tilde D(\a)\\
  \t{where }\tilde D(\a)\triangleq\frac{C(\a)}{(M-1)^{1/2}+0.12+0.11/(M-1)^{1/2}}
  $$

* reject null hypothesis if $\mathcal P_k$ versus $f_k$ falls outside of lines at any $f_k$

# Reflection Boundary Conditions and DCT-II

$$
X_0,\cdots,X_{N-1}X_{N-1},\cdots,X_0\\
\tilde S^{(dct)}=\frac 2 N\lrbra(){\sumsubtri t 0{N-1}X_t\cos  \lrbra(){\frac{\pi k[2t+1]}{2N}}}^2\\
\tilde f_k=k/2N
$$
Compare above with type-II discrete cosine tranform(DCT-II)
$$
C_k=\lrbra(){\frac{2-\delta_k}{N}}^{1/2}\sumsubtri t 0 {N-1}\cos\lrbra(){\frac{\pi k[2t+1]}{2N}},k=0,\cdots,N-1
$$
Compare
$$
\tilde S^{dct}(\tilde f_k)=\equtwo{C_k^2}{k=1,\cdots,N-1}{2C_0^2}{k=0}
$$
DCT-based Periodogram
$$
\h S^{(dct)}(\tilde f_k)\triangleq C_k^2,k=0,\cdots,N-1
$$
Compare
$$
E\bra{\h S^{(dct)}(f_k)}=E\bra{\h S^{(p)}(\tilde f_k)}-\frac{2}{N\sin(\pi k/N)}\sumsubtri \tau 1 {N-1}s_\tau\sin(\pi \tau k/N)\\
\liminf N E\bra{\h S^{(dct)}(f)}\rightarrow S(f)
$$
for large $N$
$$
\h S^{(dct)}(\tilde f_k)\mathop =^\d S(\tilde f_k)\chi_1^2\\
\h S\kp(\tilde f_k)\mathop =^\d \frac{S(\tilde f_k)}2\chi_2^2\\
\var\bra{\h S^{(dct)}(\tilde f_k)}\approx2S^2(\tilde f_k)\approx S^2(\tilde f_k)
$$

[Back](#up)

# Computational Details

Four ways






