---
title: "UW 520"
subtitle: "Lecture 3 - Notes"
author: "Lin Gui"
output:
  html_document:
    toc: true
    number_sections: true
---

<span id="jump"></span>

-   $\sumsub{f}{}$: sum or integral

[Back](course_uw_520.html)

# Continuous Time/Discrete Frequency: FS

## example

$$
g_p(t)=\frac{1-\phi^2}{1+\phi^2-2\phi\cos(t)}\\
g_{p,m}=\sumsubtri n {-m} m G_n\etpi{f_nt}=1+2\sumsubtri n 1 m \phi^n\cos(nt)
$$

$g_p$ and its Fourier approximation

[up](#jump)

# Continuous Time/Continuous Frequency: FT

## Similarity Theorem

$$
\abs a^{1/2}g(at)\leftrightarrow G(f/a)/\abs a^{1/2}
$$

## Equivalent Width

$$
\text{width}_e\bra g=\intinf g(t)\d t/g(0)\\
=\frac 1 {\text{width}_e\bra G}
$$

## Fundamental Uncertainty Relationship

**if $g$ real and nonnegative with unit area, then $g$ is probability density function**

else, form $\tilde g(t)=g(t)/\intinf g(t)\d t$
$$
\sigma_g^2\times\sigma^2_G\geq 1/16\pi^2
$$
**with equality holding only in the Gaussian case**

## Convolution Theorem

-   example one
    $$
    h(t)=\sumsubtri l 1 LA_l\cos(2\pi f_l t+\phi_l)\\
    g(t)=\frac 1 {\sqrt{2\pi\sigma^2}}e^{-t^2/2\sigma^2}\\
    g*h(t)=\sumsubtri l 1 L e^{-(\sigma2\pi f_l)^2/2}A_lcos(2\pi f_l t+\phi_l)
    $$

    -   freqencies $f_l$ and phases $\phi_l$ are unchanged
    -   to 1 as $f_l\rightarrow 0$, to 0 as $f_l\rightarrow\infty$
    -   reduce amplitudes of high frequency terms

-   example two
    $$
    r(t)=\equtwo {1/2\delta}{-\delta\leq t\leq \delta} 0 {\text{otherwise}}
    $$



## Cross and Autocorrelations

$$
g\star h^*(t)\triangleq\intinf g(u+t)h^*(u)du\leftrightarrow G(\cdot)H^*(\cdot)\\
g\star g^*(t)\leftrightarrow\abs{G(\cdot)}^2
$$

**autocorrelation width**
$$
\text{width}_a\bra{g(\cdot)}=\text{width}_e\bra{g\star g^*(\cdot)}
$$
[up](#jump)

# Discrete Time/Continuous Frequency: DTFT

$g(\cdot)$ has finite energy

$\bra{g_t}\leftrightarrow G_p(\cdot)$
$$
\bra{g_t\times r_t}\leftrightarrow(2m+1)G_p*D_{2m+1}
$$

## $(2m+1)D_{2m+1}$: sinc

-   central lobe
-   sidelobes
-   cause: smear and leakage

## Cesara Sums

general method
$$
\t{sequence }\cdots,u_{-1},u_0,u_1,\cdots\\
s_m=\sumsym t m\\
a_m=\frac 1 m \sumsubtri j 0 {m-1} s_j=\sumsubtri {t}{-m}m\lrbra (){1-\frac{\abs t}{m}}u_t\\
\t{if }s_m\rightarrow s, \t{then }a_m\rightarrow s
$$
example
$$
G_{p,m}^{(C)}(f)=\sumsubtri t {-m}m(1-\frac{\abs t} m)g_t\etpin {ft}\rightarrow G_p(f)\\
=m\intsym{1/2} G_p(f')D_m^2(f'-f)\d f'
$$
_Fejer's kernel_

Advantage and disadvantage

-   $D^2_m$ smaller sidelobes
-   nonnegative sidelobes
-   wider central lobe

## Aliasing

$\bra{g_t}\leftrightarrow G_p(\cdot)$

$g(\cdot)\leftrightarrow G(\cdot)$ and $g_t=g(t\Delta_t)$
$$
G_p(f)=\suminf k G(f+k/\Delta_t)
$$
highest $f$ that is not an alias one 
$$
f_n=\frac 1 {2\Delta t}
$$
[up](#jump)

# Discrete/Continuous Concentration Problem

$g_t$ real-valued & time-limited to $t=0,\dots,N-1$

**How close can $G_p()$ be to bandlimited?**

## concentration measure

$$
\b^2(W)=\frac{\intsym W\abs{G_p(f)}^2\d f}{\intsym {1/2}\abs{G_p(f)}^2}\\
\intsym W\abs{G_p(f)}^2\d f=g^TAg\\
\intsym{1/2}|G_p(f)|^2\d f=g^T g\\
g=[g_0,\dots,g_{N-1}]^T,A_{mn}=\frac{\sin(2\pi W(m-n))}{\pi(m-n)}\\
\b^2(W)=\frac{g^TAg}{g^Tg}
$$

## maximize $\beta^2(W)$

$$
Ag=\beta^2(W)g\\
Ag=\lambda g\\
0<\lambda_{N-1}(N,W)<\cdots<\lambda_0(N,W)<1
$$

>   Why $\lambda_0(N,W)<1$

**first $2NW$ eigenvalues close to 1, after which $\lambda_k(N,W)$'s fall rapidly to 0.**

[up](#jump)

# Discrete Time/Discrete Frequency: DFT

[up](#jump)