---
title: "UW 520"
subtitle: "Lecture 1 - Notes"
author: "Lin Gui"
output:
  html_document:
    toc: true
    number_sections: true
---

<span id="jump"></span>

[Back](course_uw_520.html)

# Lagged Scatter Plot

$x_{t+1}$ versus $x_t$

$\hat \rho_k$: sample ACS

[up](#jump)

# Frequency Domain Modeling

$$
X_t=\mu+\sumsub{j=1}{N/2}[A_j\cos(2\pi f_jt)+B_j\sin(2\pi f_j t)]\\
E[A_j]=E[B_j]=0\\
\var{[A_j]}=\var[B_j]=\sigma^2\\
\cov\{A_j,A_k\}=\cov\{B_j,B_k\}=0,j\neq k\\
\cov\{A_j,B_k\}=0\\
$$

Spectrum
$$
\rho_k=\frac{\sumsub{j=1}{N/2}\sigma_j^2\cos(2\pi f_jk)}{\sumsub{j=1}{N/2}\sigma_j^2}\\
S_j\triangleq \sigma_j^2\\
\sumsub{j=1}{N/2}S_j=\sigma^2
$$
[up](#jump)

# Nonparametric Estimation of $S_j$

$S_j=var\{A_j\}=var\{B_j\}$$

-   yields
    $$
    A_j=\frac 2 N\sumsub{t=0}{N-1}X_t\cos(2\pi f_jt)\\
    B_j=\frac 2 N\sumsub{t=0}{N-1}X_t\sin(2\pi f_j t)
    $$

-   $\hat S_j$
    $$
    \hat S_j\triangleq\frac {A_j^2+B_j^2}{2}
    $$

-   assumption of $S_j$
    $$
    S_j(\alpha,\beta)=\frac \beta{1+\alpha^2-2\alpha\cos(2\pi f_j)}
    $$

    >   Why this assumption?

    estimate
    $$
    \hat S_j(\hat\alpha,\hat\beta)=\frac {\hat\beta}{1+\hat\alpha^2-2\hat\alpha\cos(2\pi f_j)}
    $$

-   $\hat\alpha,\hat\beta$

    $\rho_1\approx\alpha$, so let $\hat\alpha=\hat\rho_1$

    From requirment:
    $$
    \sumsub{j=1}{N/2}\hat S_j(\hat\alpha,\hat\beta)=\frac 1 N\sumsub{t=1}{N}(X_t-\overline X)^2= \hat\sigma^2
    $$
    yileds estimation
    $$
    \hat\beta=\hat\sigma^2\left(\sumsub{j=1}{N/2}\frac 1{1+\hat\alpha^2-2\hat\alpha\cos(2\pi f_j)}\right)^{-1}
    $$





-   Stationary
    $$
    E\bra {X_t}=\mu\\
    \var\bra{X_t}=\sigma^2\\
    \cov\bra{X_{t+k},X_t} =\rho_k\sigma^2
    $$

-   extension model under stationary
    $$
    X_t=\mu+\intsym {1/2} \etpi{ft}\d Z(f)
    $$
    define $S(f)$
    $$
    \var\bra{\d Z(f)}=S(f)\d f
    $$
    fundamental relationship
    $$
    \intsym{1/2}S(f)\d f=\sigma^2\\
    \rho_k\sigma^2=\intsym{1/2}S(f)\etpi{fk}\d f\\
    S(f)=\sigma^2\suminf k \rho_k\etpin{fk}
    $$
    basic estimator - periodogram
    $$
    \hat S^{(p)}(f)\triangleq \frac 1 N\abs{\sumsub{t=0}{N-1}(X_t-\overline X)\etpin{ft}}^2
    $$

    >   Where to derive it?

    -   badly biased
    -   $\var\bra{\h S^{(p)}(f)}=S^2(f)$ as $N\rightarrow\infty$ if $0<f<\frac 1 2 $

-   − testing theories (e.g., wind data)
    − exploratory data analysis (e.g., rainfall data) 

    − discriminating data (e.g., neonates)
    − diagnostic tests (e.g., ARIMA modeling)
    − assessing predictability (e.g., atomic clocks)

[up](#jump)